services:
  postgres:
    container_name: postgres
    image: postgis/postgis:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bussiness-finder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    # command: postgres -c 'max_connections=10000'

volumes:
  postgres:
    driver: local