version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - 8081:8080
    command:
      - start-dev # for dev
      - --import-realm
    volumes:
      - ./config/:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      ROOT_LOG_LEVEL: DEBUG #TRACE
      # KC_PROXY: edge # for prod
      # KC_HOSTNAME: localhost # for prod
