version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: don
      MYSQL_PASSWORD: don
