version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test1,test2
      MYSQL_USER: don
      MYSQL_PASSWORD: don
