version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    expose:
      - "5433"
    command: -p 5433
    ports:
      - 5433:5433
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
    driver: local
