version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    command: -p 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  postgres:
    driver: local
