services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: >
      --requirepass "redis"
    ports:
      - '6379:6379'

volumes:
  redis:
    driver: local
